name: Release to Nuget

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-dir: ./SampleCSharpNuget/ClassLibrary1
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: build with dotnet
      working-directory: ${{env.working-dir}}
      run: dotnet build  --configuration  Release --version-suffix $(date +%Y%m%d%H%M%S)
      shell: bash
      
    - name: List files before build
      run: |
          pwd 
          ls -a 
    - name: Publish nuget
      run: |
           for f in ${{env.working-dir}}/bin/Release/*.nupkg
           do
             curl -vX PUT -u "mohitjohri:${{ secrets.GHPackagesToken }}" -F package=@$f https://nuget.pkg.github.com/mohitjohri/
           done
      shell: bash
