name: Release to Nuget

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-dir: ./SampleCSharpNuget/ClassLibrary1
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: List files before build
      run: |
          pwd 
          ls -a
    - name: build with dotnet
      working-directory: ${{env.working-dir}}
      run: dotnet build  --configuration  Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
      shell: bash
    - name: Publish nuget
      run: |
           for f in ./[repository]/bin/Release/*.nupkg
           do
             curl -vX PUT -u "[user]:${{ secrets.GHPackagesToken }}" -F package=@$f https://nuget.pkg.github.com/[user]/
           done
      shell: bash
  