name: Release to Nuget

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Nuget package
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/ZeroWasteTeam/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
    - name: Get Release Version
      id: compute-release-version
      uses: ZeroWasteTeam/actions/compute-version@master
      with:
          build-branch: ${{ github.event.client_payload.buildBranch }}
    - name: Build project
      run: |  
          cd SampleCSharpNuget
          dotnet build -c Release 

    - name: Generate a NuGet package
      run: |  
          cd SampleCSharpNuget 
          dotnet pack --no-build -c Release -o out --version ${{ steps.compute-release-version.outputs.version}}

      
    - name: List files after build
      run: |
          pwd 
          ls -R 
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./SampleCSharpNuget/out/*.nupkg --skip-duplicate --no-symbols true
