name: Release to Nuget

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Nuget package
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/ZeroWasteTeam/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        

    - name: Build project
      run: |  
          cd SampleCSharpNuget
          dotnet pack -c Release -o out  

    - name: Generate a NuGet package
      run: dotnet pack --no-build -c Release -o . 
      
    - name: List files before build
      run: |
          pwd 
          ls -a 
    - name: Push generated package to GitHub registry
      run: dotnet nuget push *.nupkg 
